name: Build Spidi Clicker
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build APK
        # Этот скрипт найдет build.gradle и запустит сборку там, где он лежит
        run: |
          BUILD_FILE=$(find . -name "build.gradle" | head -n 1)
          PROJECT_ROOT=$(dirname $BUILD_FILE)
          echo "Project found in $PROJECT_ROOT"
          chmod +x gradlew
          ./gradlew assembleDebug -p $PROJECT_ROOT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Spidi-Clicker-APK
          path: "**/*.apk"
